// Run with Electron, not `node`: native @MainActor operations need AppKit's loop.
const { app } = require('electron')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
let temporary
const timeout = setTimeout(() => { console.error('Native ABI smoke timed out'); app.exit(1) }, 20_000)
app.whenReady().then(async () => {
  const source = path.resolve('build/computer-use-runtime')
  temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'cozea-cu-relocated-'))
  fs.cpSync(source, temporary, { recursive: true })
  const native = require(path.join(temporary, `cozea_computer_use.darwin-${process.arch}.node`))
  assert.equal(native.abiVersion(), 2)
  const tools = JSON.parse(native.listTools()).tools
  assert.equal(tools.length, 9)
  assert.ok(tools.find((tool) => tool.name === 'get_app_state').inputSchema.properties.include_screenshot)
  const diagnostics = JSON.parse(await native.diagnostics())
  assert.equal(diagnostics.supported, true)
  assert.equal(diagnostics.abiVersion, 2)
  assert.equal(native.configureSession('smoke', JSON.stringify({ revision: '1', allowedTools: ['click'], allowGlobalPointer: false })), true)
  native.cancelRequest('smoke', 'cancel-before-call')
  const result = JSON.parse(await native.callTool('smoke', 'click', '{"app":"Fixture","element_index":"1"}',
    '{"requestID":"cancel-before-call","policyRevision":"1"}'))
  assert.equal(result.isError, true)
  assert.equal(JSON.parse(result.content[0].text).error, 'CANCELLED')
  native.revokeSession('smoke')
  assert.equal(native.configureSession('smoke', JSON.stringify({ revision: '1', allowedTools: ['click'], allowGlobalPointer: false })), false)
  await native.resetAll()
  clearTimeout(timeout)
  console.log('Native ABI 2, relocated resources, async diagnostics and pre-admission revocation passed. No desktop input was sent.')
  app.exit(0)
}).catch((error) => { console.error(error); clearTimeout(timeout); app.exit(1) })
app.on('will-quit', () => { if (temporary) fs.rmSync(temporary, { recursive: true, force: true }) })
