import type {
  LocalProjectDTO,
  LocalProjectId,
  LocalProjectWorkspaceOutcome,
} from "../../shared/localProjectTypes";

export const localProject: LocalProjectDTO = {
  projectId: `lpj_${"a".repeat(32)}` as LocalProjectId,
  name: "Personal",
  localName: "Personal",
  fallbackName: "Personal",
  slug: "personal",
  hidden: false,
  status: "active",
  cloudProjectId: null,
  sharedName: null,
  sharedStatus: null,
  sharedIdentityKey: null,
  sharedObservedAt: null,
  createdAt: 1,
  updatedAt: 1,
};
export const localOutcome: LocalProjectWorkspaceOutcome = {
  project: localProject,
  operationId: "create_one",
  reusedExisting: false,
  workspace: {
    workspaceId: "workspace_one",
    projectId: localProject.projectId,
    label: null,
    displayPath: "/tmp/projects/personal",
    rootPath: "/tmp/projects",
    projectRootRelativePath: "personal",
    projectRootPath: "/tmp/projects/personal",
    gitRootPath: "/tmp/projects/personal",
    gitOriginUrl: null,
    gitRepoIdentity: null,
    verificationStatus: "verified",
    verificationReason: null,
    verifiedAt: 1,
    source: "create",
    storageOwnership: "managed",
    managedRootId: "root_one",
    markerPolicy: "required",
    isActive: true,
    workspaceRevision: 1,
    createdAt: 1,
    updatedAt: 1,
    lastOpenedAt: null,
  },
};
