/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PtyOptions {
  executable: string
  args: Array<string>
  cwd: string
  cols: number
  rows: number
  env?: Record<string, string>
}
export declare function spawn(options: PtyOptions, onData: (data: string) => void, onExit: (exitCode: number) => void): NativePty
export declare function checkSubprocessActivity(pid: number): boolean
export declare class NativePty {
  write(data: string): void
  resize(cols: number, rows: number): void
  kill(): void
  getPid(): number
}
